language: node_js
node_js:
  - 0.8
  - "0.10"
  - 0.12
  - iojs
before_install:
  - npm install -g npm
notifications:
  email:
    recipients:
      - andris@kreata.ee
    on_success: change
    on_failure: change
